# Docker Compose Configuration
# https://docs.docker.com/compose/

version: '3'

services:
  db:
    container_name: postgres
    restart: always
    image: postgres:14
    ports:
      - '${DATABASE_PORT}:${DOCKER_PORT}'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
